const projects = [
  {
    id: 'loveui',
    title: 'LoveUI',
    img: '/loveui/project3.webp',
    link: '/projects/loveui',
    date: '2026',
    liveLink: 'https://loveui.dev',
    seoTitle: 'LoveUI Case Study: React UI Library | Ohio Web Developer',
    seoDescription: 'LoveUI is an open-source React and Tailwind UI library case study by Ohio web developer Connor Love, with docs, components, blocks, charts, icons, and AI agent skills.',
    seoKeywords: [
      'LoveUI',
      'LoveUI case study',
      'LoveUI React components',
      'React UI library',
      'Tailwind CSS components',
      'Base UI components',
      'copy paste UI components',
      'open source design system',
      'product interface components',
      'SaaS UI components',
      'dashboard UI components',
      'AI coding agent skills',
      'AI interface design workflow',
      'component registry',
      'Connor Love LoveUI',
      'Ohio web developer LoveUI',
      'Columbus Ohio web developer',
    ],
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    topics: [
      'Open-source React UI library',
      'Tailwind CSS components',
      'Base UI interaction primitives',
      'Copy-paste component registry',
      'Product interface blocks',
      'Chart and dashboard blocks',
      'AI coding agent skill pack',
      'AI-readable documentation',
    ],
    intro: [
      'LoveUI is a source-first React UI library for product teams, developers, and AI-assisted workflows.',
      'It brings docs, components, blocks, charts, icons, and LoveUI Skills into one clear product surface.',
      'It helps teams start polished interface work faster, inspect the code clearly, and adapt every piece inside a real codebase.',
    ],
    images: [
      {
        src: '/loveui/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/loveui/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/6.webp',
        tag: 'big',
        isRight: true,
      },
    ],
    desc: [
      'LoveUI is an open-source React UI library for building polished product interfaces. It gives teams documentation, components, blocks, charts, icons, and AI agent workflows in one product system.',
      'The product is source-first: developers copy components and blocks into their own app, then edit the code directly. That makes LoveUI useful for teams that want good defaults without giving up control of styling, structure, or behavior.',
      'The docs explain how to install LoveUI, use React and Tailwind CSS components, customize tokens, handle accessibility, and compose real screens from primitives like buttons, forms, dialogs, menus, tabs, tables, toasts, and tooltips.',
      'LoveUI also includes complete blocks for marketing pages and application UI, including headers, heroes, pricing, FAQs, contact sections, auth screens, onboarding flows, stats, command palettes, sidebars, and chart blocks for dashboards.',
      'LoveUI Skills gives AI coding agents design rules, workflow steps, quality checks, and focused skills for building, auditing, polishing, adapting, hardening, clarifying, extracting, and learning LoveUI interfaces.',
      'The product direction is clear: searchable examples, AI-readable content, open-source code, and a simple path from component to production interface.',
    ],
  },
  {
    id: 'lovechat',
    title: 'LoveChat',
    img: '/lovechat/project4.webp',
    link: '/projects/lovechat',
    date: '2026',
    liveLink: undefined,
    githubLink: 'https://github.com/loveconnor/lovechat',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/lovechat/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovechat/7.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'LoveChat is a full-stack AI chat platform built with a modern monorepo architecture, combining real-time conversations with advanced AI workflows.',
      'It supports session-based chat, branching conversations, memory systems, file uploads, and rich content rendering including charts, math, and images.',
      'The system integrates model routing, web search, and long-term memory to create a highly dynamic and extensible AI product experience.',
    ],
  },
  {
    id: 'lyceum',
    title: 'Lyceum',
    img: '/lyceum/project5.webp',
    link: '/projects/lyceum',
    date: '2026',
    liveLink: undefined,
    githubLink: 'https://github.com/loveconnor/lyceum',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/lyceum/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lyceum/7.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Lyceum is an AI-powered learning platform designed to guide users from interest to mastery through personalized learning paths and interactive labs.',
      'The system combines structured modules, hands-on exercises, and an integrated AI assistant to support real-time learning and feedback.',
      'With progress tracking, reflections, and adaptive recommendations, Lyceum creates a fully dynamic and personalized education experience.',
    ],
  },
  {
    id: 'lovesans',
    githubLink: 'https://github.com/loveconnor/lovesans',
    title: 'LoveSans',
    img: '/lovesans/project1.webp',
    link: '/projects/lovesans',
    date: '2026',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/lovesans/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/5.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'LoveSans is a custom sans-serif typeface system designed for modern digital products, branding, and interface design.',
      'The project focuses on creating a consistent typographic foundation across web applications, balancing readability with strong visual identity.',
      'Built as both a design and engineering exercise, it bridges typography with real-world UI implementation and product usage.',
    ],
  },
  {
    id: 'connorvault',
    githubLink: 'https://github.com/loveconnor/connorvault',
    title: 'ConnorVault',
    img: '/connorvault/project2.webp',
    link: '/projects/connorvault',
    date: '2026',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/connorvault/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/connorvault/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/connorvault/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'ConnorVault is a full-stack API key management and proxy platform that centralizes provider credentials behind secure internal keys.',
      'It enables developers to route API requests through a controlled proxy, monitor usage, and manage key lifecycles across environments.',
      'With built-in telemetry, environment separation, and key-level control, it provides a secure infrastructure layer for modern applications.',
    ],
  },
  /*
    {
      id: 'prismo',
      title: 'Prismo',
      img: '/project6/project6.webp',
      link: '/projects/prismo',
      date: '2025',
      primary: '#0e0063',
      accentColor: '#f0f4f1',
      secondary: '#fbfbfc',
      fillColor: '#e1e1f9',
      menuColor: '#170053',
      menuFontColor: '#f0f4f1',
      fluidColor: '#E8FFC8',
      images: [
        {
          src: '/project6/video.mp4',
          tag: 'video',
          isRight: true,
        },
        {
          src: '/project6 /1.webp',
          tag: 'big',
          isRight: false,
        },
        {
          src: '/project6/2.webp',
          tag: 'big',
          isRight: false,
        },
        {
          src: '/project6/3.webp',
          tag: 'big',
          isRight: false,
        },
      ],
      desc: [
        'Prismo is an AI-powered educational platform combining interactive coding labs with real-time execution and intelligent feedback.',
        'It supports multiple languages, adaptive learning systems, and AI-driven code review using providers like Claude and Gemini.',
        'The platform integrates analytics, gamification, and an extensible widget system to create a fully interactive learning environment. :contentReference[oaicite:5]{index=5}',
      ],
    },
    */
];
export default projects;
