const projects = [
  {
    id: 'loveui',
    title: 'LoveUI',
    img: '/loveui/project3.webp',
    link: '/projects/loveui',
    date: '2026',
    liveLink: 'https://loveui.dev',
    seoTitle: 'LoveUI Case Study: React UI Library | Ohio Web Developer',
    seoDescription: 'LoveUI is an open-source React and Tailwind UI library case study by Ohio web developer Connor Love, with docs, components, blocks, charts, icons, and AI agent skills.',
    seoKeywords: [
      'LoveUI',
      'LoveUI case study',
      'LoveUI React components',
      'React UI library',
      'Tailwind CSS components',
      'Base UI components',
      'copy paste UI components',
      'open source design system',
      'product interface components',
      'SaaS UI components',
      'dashboard UI components',
      'AI coding agent skills',
      'AI interface design workflow',
      'component registry',
      'Connor Love LoveUI',
      'Ohio web developer LoveUI',
      'Columbus Ohio web developer',
    ],
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    topics: [
      'Open-source React UI library',
      'Tailwind CSS components',
      'Base UI interaction primitives',
      'Copy-paste component registry',
      'Product interface blocks',
      'Chart and dashboard blocks',
      'AI coding agent skill pack',
      'AI-readable documentation',
    ],
    intro: [
      'LoveUI is a source-first React UI library for product teams, developers, and AI-assisted workflows.',
      'It brings docs, components, blocks, charts, icons, and LoveUI Skills into one clear product surface.',
      'It helps teams start polished interface work faster, inspect the code clearly, and adapt every piece inside a real codebase.',
    ],
    images: [
      {
        src: '/loveui/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/loveui/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/loveui/6.webp',
        tag: 'big',
        isRight: true,
      },
    ],
    desc: [
      'LoveUI is an open-source React UI library for building polished product interfaces. It gives teams documentation, components, blocks, charts, icons, and AI agent workflows in one product system.',
      'The product is source-first: developers copy components and blocks into their own app, then edit the code directly. That makes LoveUI useful for teams that want good defaults without giving up control of styling, structure, or behavior.',
      'The docs explain how to install LoveUI, use React and Tailwind CSS components, customize tokens, handle accessibility, and compose real screens from primitives like buttons, forms, dialogs, menus, tabs, tables, toasts, and tooltips.',
      'LoveUI also includes complete blocks for marketing pages and application UI, including headers, heroes, pricing, FAQs, contact sections, auth screens, onboarding flows, stats, command palettes, sidebars, and chart blocks for dashboards.',
      'LoveUI Skills gives AI coding agents design rules, workflow steps, quality checks, and focused skills for building, auditing, polishing, adapting, hardening, clarifying, extracting, and learning LoveUI interfaces.',
      'The product direction is clear: searchable examples, AI-readable content, open-source code, and a simple path from component to production interface.',
    ],
  },
  {
    id: 'clove-colors',
    title: 'Clove Colors',
    img: '/clove-colors/project.webp',
    imgAlt: 'Clove Colors palette builder with five editable color columns',
    link: '/projects/clove-colors',
    date: '2026',
    liveLink: 'https://colors.connorlove.com',
    githubLink: 'https://github.com/loveconnor/clove-colors',
    seoTitle: 'Clove Colors Case Study: Color System Workbench | Connor Love',
    seoDescription: 'Clove Colors is a free color workbench by Connor Love for creating palettes, semantic themes, color ramps, WCAG contrast reports, previews, and production-ready design tokens.',
    seoKeywords: ['Clove Colors', 'color palette generator', 'design token generator', 'semantic color system', 'WCAG contrast checker', 'light and dark theme builder', 'color palette MCP'],
    primary: '#172A3A',
    accentColor: '#F4F1DE',
    secondary: '#F3B61F',
    fillColor: '#F4F1DE',
    menuColor: '#F3B61F',
    menuFontColor: '#172A3A',
    fluidColor: '#5FB49C',
    topics: ['Color palette workbench', 'Semantic color systems', 'WCAG contrast reports', 'Design token exports', 'Light and dark themes', 'Read-only MCP tools'],
    intro: [
      'Clove Colors is a free color workbench for designers and developers.',
      'It turns a palette into color ramps, light and dark themes, contrast reports, previews, and design tokens that are ready to use in a product.',
      'It works without an account and keeps saved palettes in the browser.',
    ],
    images: [
      {
        src: '/clove-colors/1.webp',
        tag: 'big',
        isRight: false,
        alt: 'Clove Colors palette builder with controls for harmony, color count, history, generation, and saving',
      },
      {
        src: '/clove-colors/2.webp',
        tag: 'big',
        isRight: false,
        alt: 'Clove Colors system builder showing semantic color roles and coordinated color ramps',
      },
      {
        src: '/clove-colors/3.webp',
        tag: 'big',
        isRight: false,
        alt: 'Clove Colors curated palette library with search and measurable filters',
      },
      {
        src: '/clove-colors/4.webp',
        tag: 'big',
        isRight: false,
        alt: 'Clove Colors visualizer applying a palette to a sample marketing page',
      },
    ],
    desc: [
      'Clove Colors helps designers and developers turn a group of colors into a complete product color system.',
      'You can create and edit a palette, assign colors to clear roles, build coordinated ramps, and check exact foreground and background pairs against WCAG contrast rules.',
      'The visualizer applies the palette to sample marketing, dashboard, and mobile screens. Exports are available as CSS, Tailwind, design-token JSON, or plain JSON.',
      'The site also includes 24 original curated palettes and read-only MCP tools. It has no accounts or database, and palettes saved in the app stay in the browser.',
    ],
  },
  {
    id: 'tokenizer',
    title: 'Tokenizer',
    img: '/tokenizer/project.webp',
    imgAlt: 'Tokenizer comparison showing token counts across ten tokenizers',
    link: '/projects/tokenizer',
    date: '2026',
    liveLink: 'https://tokenizer.connorlove.com',
    githubLink: 'https://github.com/loveconnor/tokenizer',
    seoTitle: "Connor's Tokenizer Case Study: Interactive Token Comparison",
    seoDescription:
      "Connor's Tokenizer is a browser-based tool by Connor Love for comparing a byte-lossless Unigram tokenizer with nine established tokenizer baselines using text and reproducible benchmarks.",
    seoKeywords: [
      "Connor's Tokenizer",
      'tokenizer comparison',
      'Unigram tokenizer',
      'token count comparison',
      'multilingual tokenizer benchmark',
      'browser tokenizer tool',
      'tokenizer research workbench',
    ],
    primary: '#171717',
    accentColor: '#F7F7F5',
    secondary: '#F0EDE7',
    fillColor: '#F7F7F5',
    menuColor: '#A6633C',
    menuFontColor: '#FFFFFF',
    fluidColor: '#A6633C',
    topics: ['Byte-lossless Unigram tokenizer', 'Interactive token comparison', 'Ten tokenizer baselines', 'Multilingual benchmarks', 'Browser-local processing', 'Reproducible research'],
    intro: [
      "Connor's Tokenizer is an interactive browser tool for comparing how ten tokenizers split and count text.",
      "It places Connor's byte-lossless Unigram tokenizer beside nine established baselines and shows every result in one view.",
      'The site also includes a fixed, reproducible benchmark for compression, multilingual text, robustness, and speed.',
    ],
    images: [
      {
        src: '/tokenizer/1.webp',
        tag: 'big',
        isRight: false,
        alt: "Connor's Tokenizer comparing token counts for a prose sample across ten tokenizers",
      },
      {
        src: '/tokenizer/2.webp',
        tag: 'big',
        isRight: false,
        alt: "Connor's Tokenizer comparing multilingual text and showing the local token output",
      },
      {
        src: '/tokenizer/3.webp',
        tag: 'big',
        isRight: false,
        alt: "Connor's Tokenizer benchmark suite showing the fixed corpus size, source bytes, tracks, and source groups",
      },
    ],
    desc: [
      "Connor's Tokenizer is an interactive tool for comparing a byte-lossless Unigram tokenizer with nine established tokenizer baselines.",
      'You can enter text or choose a prepared example to compare token counts, token boundaries, and simple ratios across all ten tokenizers. The work runs locally in a browser worker, so entered text is not sent to an AI provider.',
      'A separate benchmark uses 2,116 fixed records to compare compression, multilingual coverage, robustness, and throughput. The repository includes source revisions, licenses, hashes, and scripts needed to reproduce the results.',
      'The project keeps its claim narrow: token counts and benchmark metrics can compare tokenizers, but they do not prove that a language model will be better or cheaper to train.',
    ],
  },
  {
    id: 'lovesans',
    githubLink: 'https://github.com/loveconnor/lovesans',
    title: 'LoveSans',
    img: '/lovesans/project1.webp',
    link: '/projects/lovesans',
    date: '2026',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/lovesans/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/lovesans/5.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'LoveSans is a custom sans-serif typeface system designed for modern digital products, branding, and interface design.',
      'The project focuses on creating a consistent typographic foundation across web applications, balancing readability with strong visual identity.',
      'Built as both a design and engineering exercise, it bridges typography with real-world UI implementation and product usage.',
    ],
  },
  /*
    {
      id: 'prismo',
      title: 'Prismo',
      img: '/project6/project6.webp',
      link: '/projects/prismo',
      date: '2025',
      primary: '#0e0063',
      accentColor: '#f0f4f1',
      secondary: '#fbfbfc',
      fillColor: '#e1e1f9',
      menuColor: '#170053',
      menuFontColor: '#f0f4f1',
      fluidColor: '#E8FFC8',
      images: [
        {
          src: '/project6/video.mp4',
          tag: 'video',
          isRight: true,
        },
        {
          src: '/project6 /1.webp',
          tag: 'big',
          isRight: false,
        },
        {
          src: '/project6/2.webp',
          tag: 'big',
          isRight: false,
        },
        {
          src: '/project6/3.webp',
          tag: 'big',
          isRight: false,
        },
      ],
      desc: [
        'Prismo is an AI-powered educational platform combining interactive coding labs with real-time execution and intelligent feedback.',
        'It supports multiple languages, adaptive learning systems, and AI-driven code review using providers like Claude and Gemini.',
        'The platform integrates analytics, gamification, and an extensible widget system to create a fully interactive learning environment. :contentReference[oaicite:5]{index=5}',
      ],
    },
    */
];
export default projects;
